# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='mail', max_length=32, verbose_name='gender')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'username',
                'verbose_name_plural': 'usernames',
                'ordering': ['-c_time'],
            },
        ),
    ]
