# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-17 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190717_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_modify_date',
        ),
    ]
